#
# ELK (Elasticsearch Logstash Kibana)
# References: https://www.docker.elastic.co/
# Maintained By: Eric Chin
#

version: '3'
services:
  jdk:
    build:
      context: ./docker/jdk
      dockerfile: Dockerfile
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "81:80"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    ports:
      - 5601:5601
  logstash:
    build:
      context: ./docker/logstash
      dockerfile: Dockerfile